### ISSUE TITLE
flattenChildren doesn't flatten user components

### ISSUE THREAD

**Issue by Karakatiza666** [grrowl/react-keyed-flatten-children#14]
I have created a custom component that returns a fragment with some children. When flattenChildren processes this component it doesn't register it's a fragment. Is there a way to fix this? Calling `cloneElement(<MyComponent/>, { $$typeof: Symbol.for('react.fragment') })` doesn't work.

**Comment by grrowl** [comment]
I don't think so — your component is a real component in the tree, which just happens to render one child. Are you rendering multiple "custom components", returning multiple fragments of elements, which you later want to map over as a combined set of elements?

I would suggest converting your component to a function which returns an array of elements (which can have keys), then iterating/mapping and rendering, or moving your usage of flattenChildren into your custom component to do your magic there.

**Comment by grrowl** [comment]
Closing this as out of scope, since it would complicate the implementation and is fixable in user-land, but feel free to add more info if you think it'd be helpful or compelling.

**Comment by oeed** [comment]
This is what I was personally wanting to use this package for too and had presumed it to do so. For example:

```tsx
export const Child: FunctionComponent = () => {
  return (
    <>
      <p>one</p>
      <p>two</p>
    </>
  )
}

export const Wrapper: FunctionComponent<{ children?: React.ReactNode[] }> = ({ children }) => {
  return (
    <div>
      {flattenChildren(children).map((child, i) => (
        <React.Fragment key={i}>
          {child}
          <hr />
        </React.Fragment>
      ))}
    </div>
  )
}

export const Parent: FunctionComponent = () => {
  return (
    <div>
      <h1>parent</h1>
      <Wrapper>
        <Child />
        <Child />
      </Wrapper>
    </div>
  )
}
```

I want this to put an `<hr/>` after each child `<p>` element, rendering as such:

```html
<div>
  <h1>parent</h1>
  <div>
    <p>one</p>
    <hr>
    <p>two</p>
    <hr>
    <p>one</p>
    <hr>
    <p>two</p>
    <hr>
  </div>
</div>
```

But instead, it does it after each `Child` fragment:

```html
<div>
  <h1>parent</h1>
  <div>
    <p>one</p>
    <p>two</p>
    <hr>
    <p>one</p>
    <p>two</p>
    <hr>
  </div>
</div>
```

Could you perhaps please elaborate in how you see this fixed in user-land?

**Comment by grrowl** [comment]
The main reason is _your component is a real layer in the tree,_ so the React VDOM eventually looks something like this.

```jsx
<div> 
  <h1>parent</h1>
  <Wrapper> /* ReactElement */
    <div>
      <Fragment key="0">
        <Child> /* ReactElement */
          <Fragment>
            <p>one</p>
            <p>two</p>
          </Fragment>
        </Child>
      </Fragment>
      <Fragment key="1">
        <Child> /* ReactElement */
        <Fragment>
            <p>one</p>
            <p>two</p>
          </Fragment>
        </Child>
      </Fragment>
    </div>
  </Wrapper>
</div>
```

When we flatten items in `children: ReactNode[]` and we find Fragments, we know they'll just render `props.children` and it's safe to throw away the Fragment itself and flatten its children out (mimicking render behaviour). When we encounter a `ReactElement` (which is really a `{ type, props, key }` [shaped object](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L318-L325)) we don't know what will happen when it eventually renders, but [we just use `cloneElement`](https://github.com/grrowl/react-keyed-flatten-children/blob/master/index.ts#L28-L33) to re-key it and leave the `type` and `props` untouched.

Since Elements usually result in much more complex renders much more than just their `props.children`, we don't know what will eventually be returned from `<Child />` until it's rendered by React! — the alternative would be to pre-emptively render all components found in `children` and check their returned `ReactNode[]`s for `Fragment`s, then flatten _them_ out. I believe all components in the flattened children would be rendered up to twice (once to check + flatten, then again by React if not flattened).

To address this in user land, there are a few options.

## Move `Child` logic into `Parent`

Remove the `Child` layer by moving its logic into `Parent`, so they're direct children of `Wrapper`

```tsx
export const Parent: FunctionComponent = () => {
  return (
    <div>
      <h1>parent</h1>
      <Wrapper>
        <p>one</p>
        {ifTwo && <>
          <p>two</p>
        </>}
        {ifMore && <>
          <p>three</p>
          <p>four</p>
        </>}
      </Wrapper>
    </div>
  )
}
```

This would work as you expect, with `<hr />` between each `<p>`. This is overwhelmingly what I'd suggest for most non-library implementations.

## Return `ReactNode[]` from your "components"

If `<Child />` is only rendered in `flattenChildren` components, there's no performance impact to it being a function which return an array:

```
export const Child = ({ type }: { type: string }) => {
  return [
    <p key={`${type}.0`}>one</p>
    <p key={`${type}.1`}>two</p>
  ]
}

// Wrapper is unchanged

export const Parent: FunctionComponent = () => {
  return (
    <div>
      <h1>parent</h1>
      <Wrapper>
        {...child({ type: "a" })}
        {...child({ type: "b" })}
      </Wrapper>
    </div>
  )
}
```

In this example, you'll need unique keys for the returned children of `Child`. This is most suitable for flexible "block-based editor" style implementations.

## Move flatten logic into `Child` (remove `Wrapper`)

You may be able to move your flattening logic into Child. In your example, simply render `<hr />` from inside Child. Your real world scenario will probably be more complex but this approach is worth considering.
